#!/usr/bin/env python3

import os
from time import time, sleep

from can_crusher import can_crusher, spi_display, touch_screen
from can_crusher.config import Config

class CliUI:
  def __init__(self):
    print("Pi Zero Touch Screen Interface")

    self.config = Config()
    self.config.load()

    self.display = spi_display.SpiDisplay()
    self.display.test_pattern()

    if "calibration" in self.config:
      self.calibration = self.config["calibration"]
    else:
      self.calibration = touch_screen.TouchScreenCalibrator().calibrate()
      self.config["calibration"] = self.calibration
      self.config.save()
      print(repr(self.calibration))

    self.ts = touch_screen.TouchScreen(calibration=self.calibration)

    self.slides = self.display.slide_iterator()

  def notify(self, *args):
    message = args[0]

    print("GOT %s" % message)

    file_name = "output/admin/raw_565/%s.565" % message

    if not os.path.exists(file_name):
      file_name = "output/admin/raw_565/UNKNOWN.565"

    self.display.xfer_raw_565_file(file_name)
    
  def request(self):
    start_time = 0
    while True:
      current_time = time()
      delta = current_time - start_time
      if delta > 10:
        start_time = current_time
        next(self.slides)
      click = self.ts.get_button_click_scaled()
      if click is not None:
        print("GOT CLICK %s" % repr(click))
        x, y = click
        x_distance = 0
        if x < 40:
          x_distance = 40 - x
        elif x > 280:
          x_distance = x - 280

        y_distance = 0
        if y < (240-36):
          y_distance = (240-36) - y_distance
        elif y > (240-12):
          y_distance = y - (240-12)

        if x_distance <= 5 and y_distance <= 5:
          print("HIT (%d %d) %d %d" % (x, y, x_distance, y_distance) )
          return "ACT"
        else:
          print("MISS (%d %d) %d %d" % (x, y, x_distance, y_distance) )
      sleep(0.05) # 20 x a second should be good        
    
if __name__ == "__main__":
  print("STARTING can-crusher-pi") # get something in journalctl log when a service
  cc = can_crusher.CanCrusher("/dev/serial0", CliUI())
  cc.run()
