#!/usr/bin/env python3

import can_crusher.display_helper as display_helper

from glob import glob
import sys

fact_backgrounds = glob("./backgrounds/*")

facts = [
    "That British people PRONOUNCE aluminum differently because they SPELL it differently?",
    "Napolean III treasured his rare aluminum-ware, and forced his guests to eat with lowly gold-ware?",
    "When alien archeologists discover a dead Earth, that pure Aluminum will be the primary marker of the Anthropocene Era?",
    "Before Development of the BESSEMER PROCESS pure Aluminum was extremely rare?",
    "Aluminum has an Atomic Number of 13?",
    "Aluminum based antiperspirant works by clogging your sweat pores and may give you ALZHEIMERS?",
    "Canada exports over $11 billion worth of Aluminum annually.",
    "Recycling aluminum requires 95% less energy than producing it from bauxite ore.",
    "Powdered Aluminum is used in explosives and fireworks.",
    "NASA's Orion spacecraft was built with aluminum.",
    "The Aluminum Association was established in 1933.",
    "Aluminum is the 12th most abundant element in outer space.",
    ]


ads = [
    "Hershell Walker is WRONG for GEORGIA and the UNITED STATES SENATE.",
    "Reverend Warnock's DANGEROUS AGENDA is TOO MUCH for GEORGIA"
]

trivia = [
  ("What is fun to recycle and rhymes with beryllium?", "Aluminum!"),
  ("What metal caps the Washington Monument?", "Aluminum!"),
  ("Who is the world's largest Aluminum producer?", "China produces 37 million tons annually")
  
  ]

display_helper = display_helper.DisplayHelper()

def make_slides():
  for i, text in enumerate(facts):
    sys.stdout.write(".")
    display_helper.make_fact_slide(fact_backgrounds[i%len(fact_backgrounds)], "DID YOU KNOW...", facts[i])

  for i, trivia_item in enumerate(trivia):
    sys.stdout.write(".")
    display_helper.make_trivia_slide(fact_backgrounds[i%len(fact_backgrounds)], trivia_item)

  for i, attack in enumerate(ads):
    sys.stdout.write(".")
    display_helper.make_attack_slide(attack)

admin_screens = { "HOME": "Homing...",
                  "INIT": "Initializing...",
                  "FIND_CAN": "Locating Can...",
                  "CRUSH_CAN": "Crushing Can...",
                  "RELEASE_CAN": "Done. Releasing Can...",
                  "UNKNOWN": "Working..."
                  }

def make_admin():
  for cmd, msg in admin_screens.items():
    sys.stdout.write(".")
    display_helper.make_admin_slide(cmd, msg)
  display_helper.make_admin_slide("ERROR", "FATAL ERROR", (255,0,0))
  
if __name__ == "__main__":
  display_helper.make_directory_skeleton()

  if "--purge" in sys.argv:
    display_helper.purge_old_slides()

  if not "--no-slides" in sys.argv:
    sys.stdout.write("Making slide screens...")
    display_helper.old_slide_check()
    make_slides()
    print()

  if not "--no-admin" in sys.argv:
    sys.stdout.write("Making admin screens...")
    make_admin()
    
    print()
