M48
; DRILL file {KiCad 6.0.9-8da3e8f707~117~ubuntu22.04.1} date Fri 25 Nov 2022 03:55:39 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-25T15:55:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~117~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X5.7045Y-5.7256
X5.8955Y-5.7256
T2
X4.05Y-2.1457
T3
X5.6927Y-5.8449
X5.9073Y-5.8449
T0
M30
